--TABLA USUARIO
CREATE TABLE USUARIO(
    ALIAS VARCHAR(20),
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(15) NOT NULL,
    PRIMARY KEY(ALIAS)
);
--TABLA GENERO
CREATE TABLE GENERO(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);
--TABLA MUSICA
CREATE TABLE MUSICA(
    ID INT AUTO_INCREMENT PRIMARY KEY;
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USUARIO_ALIAS VARCHAR(20),
    GENERO_ID INT
);
ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_USUARIO
FOREIGN KEY(USUARIO_ALIAS) REFERENCES USUARIO(ALIAS);

ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_GENERO
FOREIGN KEY(GENERO_ID) REFERENCES GENERO(ID);

CREATE TABLE LISTA_REPRODUCCION(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(200),
    USUARIO_ALIAS VARCHAR(20),
    PRIMARY KEY(ID)
);
ALTER TABLE LISTA_REPRODUCCION ADD CONSTRAINT PK_LISTA_REP
PRIMARY KEY(ID);

CREATE TABLE LISTA_MUSICA(
    LISTA_ID INT,
    MUSICA_ID INT,
    PRIMARY KEY(LISTA_ID, MUSICA_ID)
);
ALTER TABLE LISTA_MUSICA ADD CONSTRAINT FK_LISTA_MUSICA
FOREIGN KEY(LISTA_ID) REFERENCES LISTA_REPRODUCCION(ID);

ALTER TABLE LISTA_MUSICA ADD CONSTRAINT FK_LISTA_MUSICA
FOREIGN KEY(MUSICA_ID) REFERENCES MUSICA(ID);